{{- if .Values.global.messageQueue.useCustomizedCerts }}
apiVersion: v1
kind: Secret
metadata:
  name: maestro-addon-mqtt
  namespace: {{ .Values.global.hubNamespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.global.messageQueue.certs.ca | quote }}
  tls.key: {{ .Values.global.messageQueue.certs.caKey | quote }}
{{- end }}
