{{- $clusterCA := (lookup "v1" "Secret" .Values.messageQueue.amqStreams.namespace (printf "%s-cluster-ca-cert" .Values.messageQueue.amqStreams.name)) -}}

apiVersion: v1
kind: Secret
metadata:
  name: kafka-client-certs
  namespace: '{{ .Values.global.namespace }}'
data:
{{- range $key, $value := $clusterCA.data }}
  {{- if eq $key "ca.crt" }}
  ca.crt: {{ $value }}
  {{- end }}
{{- end }}
{{ (include "kafka.client-certs" . ) | indent 2}}
