apiVersion: v1
kind: Secret
metadata:
  name: maestro-mqtt
  namespace: '{{ .Values.global.namespace }}'
stringData:
  config.yaml: |-
    brokerHost: maestro-mqtt.maestro:8883
    caFile: /secrets/certs/ca.crt
    clientCertFile: /secrets/certs/client.crt
    clientKeyFile: /secrets/certs/client.key
    topics:
      sourceEvents: sources/maestro/consumers/+/sourceevents
      agentEvents: $share/statussubscribers/sources/maestro/consumers/+/agentevents
