{{- if .Values.global.messageQueue.useCustomizedCerts }}
apiVersion: v1
kind: Secret
metadata:
  name: maestro-mq-certs
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  ca.crt: {{ .Values.global.messageQueue.certs.ca | quote }}
  server.crt: {{ .Values.global.messageQueue.certs.serverCert | quote }}
  server.key: {{ .Values.global.messageQueue.certs.serverKey | quote }}
  client.crt: {{ .Values.global.messageQueue.certs.clientCert | quote }}
  client.key: {{ .Values.global.messageQueue.certs.clientKey | quote }}
{{- end }}
