apiVersion: v1
kind: Secret
metadata:
  name: maestro-db
  namespace: '{{ .Values.global.namespace }}'
stringData:
  db.host: maestro-db.maestro
  db.port: '5432'
  db.name: maestro
  db.user: maestro
{{- if .Values.global.db.password }}
  db.password: {{ .Values.global.db.password }}
{{- else }}
  db.password: {{ randAlphaNum 16 }}
{{- end }}
