apiVersion: v1
kind: Service
metadata:
  name: maestro-mqtt
  namespace: '{{ .Values.global.namespace }}'
spec:
  ports:
  - name: mosquitto
    port: 8883
    protocol: TCP
    targetPort: 8883
  selector:
    name: maestro-mqtt
  type: ClusterIP
