apiVersion: v1
kind: Secret
metadata:
  name: maestro-kafka-config
  namespace: '{{ .Values.global.namespace }}'
stringData:
  config.yaml: |-
{{- if eq .Values.messageQueue.amqStreams.listener.type "route" }}
    bootstrapServer: {{- indent 1 (printf "%s:443" (lookup "route.openshift.io/v1" "Route" .Values.messageQueue.amqStreams.namespace (printf "%s-kafka-tls-bootstrap" .Values.messageQueue.amqStreams.name)).spec.host) }}
{{- end }}
{{- if eq .Values.messageQueue.amqStreams.listener.type "internal" }}
    bootstrapServer: {{- indent 1 (printf "kafka-kafka-bootstrap.%s:%d" .Values.messageQueue.amqStreams.namespace .Values.messageQueue.amqStreams.listener.port) }}
{{- end }}
    caFile: /secrets/certs/kafka/ca.crt
    clientCertFile: /secrets/certs/kafka/client.crt
    clientKeyFile: /secrets/certs/kafka/client.key
