apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maestro-db
  namespace: '{{ .Values.global.namespace }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.db.pvc.storageCapacity }}
{{- if .Values.global.db.pvc.storageClassName }}
  storageClassName: {{ .Values.global.db.pvc.storageClassName }}
{{- end }}
