name: PreSubmit

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - release-*

env:
  GO_VERSION: '1.21'
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: verify
        run: make verify

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: make build

  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: unit
        run: make test

  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: set image label
        id: vars
        run: |
          echo "::set-output name=label::$(git rev-parse --short ${{ github.sha }})"
      - name: build image
        run: make image
        env:
          container_tool: docker
          IMAGE_NAME: quay.io/stolostron/maestro-addon:${{ steps.vars.outputs.label }}
      - name: e2e
        run: make e2e-test
        env:
          IMAGE_NAME: quay.io/stolostron/maestro-addon:${{ steps.vars.outputs.label }}
